// source: api/grpc/account_profile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.payed_grpc.account_profiles.DebitAccountProfileRequest', null, global);
goog.exportSymbol('proto.payed_grpc.account_profiles.DebitAccountProfileResponse', null, global);
goog.exportSymbol('proto.payed_grpc.account_profiles.DebitAccountProfileStatus', null, global);
goog.exportSymbol('proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest', null, global);
goog.exportSymbol('proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest', null, global);
goog.exportSymbol('proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.payed_grpc.account_profiles.DebitAccountProfileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.payed_grpc.account_profiles.DebitAccountProfileRequest.displayName = 'proto.payed_grpc.account_profiles.DebitAccountProfileRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.payed_grpc.account_profiles.DebitAccountProfileResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.payed_grpc.account_profiles.DebitAccountProfileResponse.displayName = 'proto.payed_grpc.account_profiles.DebitAccountProfileResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.displayName = 'proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.displayName = 'proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.displayName = 'proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.payed_grpc.account_profiles.DebitAccountProfileRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    originaccountprofileid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    destinationaccountprofileid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    purpose: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.payed_grpc.account_profiles.DebitAccountProfileRequest;
  return proto.payed_grpc.account_profiles.DebitAccountProfileRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOriginaccountprofileid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDestinationaccountprofileid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurpose(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.payed_grpc.account_profiles.DebitAccountProfileRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOriginaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDestinationaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getPurpose();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 originAccountProfileId = 2;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.getOriginaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.setOriginaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 destinationAccountProfileId = 3;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.getDestinationaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.setDestinationaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double amount = 4;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string purpose = 5;
 * @return {string}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.getPurpose = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileRequest.prototype.setPurpose = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.payed_grpc.account_profiles.DebitAccountProfileResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    originaccountprofileid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    originaccountprofiletransactionid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    destinationaccountprofileid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    purpose: jspb.Message.getFieldWithDefault(msg, 6, ""),
    status: jspb.Message.getFieldWithDefault(msg, 7, 0),
    createdat: jspb.Message.getFieldWithDefault(msg, 8, 0),
    completedat: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.payed_grpc.account_profiles.DebitAccountProfileResponse;
  return proto.payed_grpc.account_profiles.DebitAccountProfileResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOriginaccountprofileid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOriginaccountprofiletransactionid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDestinationaccountprofileid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPurpose(value);
      break;
    case 7:
      var value = /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompletedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.payed_grpc.account_profiles.DebitAccountProfileResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOriginaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDestinationaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getPurpose();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 originAccountProfileId = 2;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getOriginaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setOriginaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 originAccountProfileTransactionId = 3;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getOriginaccountprofiletransactionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setOriginaccountprofiletransactionid = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.clearOriginaccountprofiletransactionid = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.hasOriginaccountprofiletransactionid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 destinationAccountProfileId = 4;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getDestinationaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setDestinationaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional double amount = 5;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional string purpose = 6;
 * @return {string}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getPurpose = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setPurpose = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional DebitAccountProfileStatus status = 7;
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getStatus = function() {
  return /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setStatus = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.clearStatus = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int64 createdAt = 8;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 completedAt = 9;
 * @return {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.getCompletedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.setCompletedat = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.clearCompletedat = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileResponse.prototype.hasCompletedat = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    reason: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest;
  return proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string reason = 7;
 * @return {string}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileRequest.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    originaccountprofileid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    originaccountprofilereversedtransactionid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    destinationaccountprofileid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    destinationaccountprofilereversedtransactionid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    reason: jspb.Message.getFieldWithDefault(msg, 7, ""),
    status: jspb.Message.getFieldWithDefault(msg, 8, 0),
    createdat: jspb.Message.getFieldWithDefault(msg, 9, 0),
    completedat: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse;
  return proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOriginaccountprofileid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOriginaccountprofilereversedtransactionid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDestinationaccountprofileid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDestinationaccountprofilereversedtransactionid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    case 8:
      var value = /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompletedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOriginaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDestinationaccountprofileid();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 originAccountProfileId = 2;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getOriginaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setOriginaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 originAccountProfileReversedTransactionId = 3;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getOriginaccountprofilereversedtransactionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setOriginaccountprofilereversedtransactionid = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.clearOriginaccountprofilereversedtransactionid = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.hasOriginaccountprofilereversedtransactionid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 destinationAccountProfileId = 4;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getDestinationaccountprofileid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setDestinationaccountprofileid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 destinationAccountProfileReversedTransactionId = 5;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getDestinationaccountprofilereversedtransactionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setDestinationaccountprofilereversedtransactionid = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.clearDestinationaccountprofilereversedtransactionid = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.hasDestinationaccountprofilereversedtransactionid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double amount = 6;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string reason = 7;
 * @return {string}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional DebitAccountProfileStatus status = 8;
 * @return {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getStatus = function() {
  return /** @type {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.payed_grpc.account_profiles.DebitAccountProfileStatus} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setStatus = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.clearStatus = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int64 createdAt = 9;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 completedAt = 10;
 * @return {number}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.getCompletedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.setCompletedat = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse} returns this
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.clearCompletedat = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.payed_grpc.account_profiles.ReverseDebitAccountProfileResponse.prototype.hasCompletedat = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest}
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest;
  return proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest}
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest} returns this
 */
proto.payed_grpc.account_profiles.FetchTransferByReferenceRequest.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.payed_grpc.account_profiles.DebitAccountProfileStatus = {
  PENDING: 0,
  SUCCESSFUL: 1,
  FAILED: 2
};

goog.object.extend(exports, proto.payed_grpc.account_profiles);
